name: ci
on: push
jobs:
  arpicee-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run: make test

      - name: build
        run: make build

  goreleaser:
    runs-on: ubuntu-latest
    needs:
      - arpicee-test-and-build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # https://github.com/goreleaser/goreleaser-action/issues/56

      - name: goreleaser
        run: |
          echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          GITHUB_ACTOR=$(echo ${GITHUB_ACTOR} | tr '[:upper:]' '[:lower:]')
          GIT_OWNER=${GITHUB_ACTOR} make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
