name: ci
on: push
jobs:
  arpicee-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run: make test

      - name: build
        run: make build
